# @package apps.todo
layout: kanban_board
add_button_color: ""
background_color: "#ffffff"
form_background_color: "#ebecf0"
remove_button_color: "#B22222"
edit_button_color: "#36454F"
save_button_color: ""
font_family: 'Times New Roman'
base_font_size: '16px'
font_color: ""
edit_remove_save_button_font_color: ""
